### ISSUE TITLE
Recent Posts Module (todo)

### ISSUE THREAD

**Issue by erikdmitchell** [erikdmitchell/pickle-divi-builder-addons#1]
- [x] Taxonomy Option (dropdown)
- [x] Excerpt length option (int)
- [x] More text option (text)
- [x] Show thumbnail option
